### PR TITLE
[ENH] Refactored gpuci_conda_retry for easier debugging with more output messages

### PR DESCRIPTION
**Pull request by rlratzel**
Refactored to possibly make it easier to read and expand, also added more messaging to hopefully help diagnose unexpected behavior in the future.

Tested with a "testConda" command that produced various output and exit codes, also ran with the actual conda to verify no regressions.

### CODE REVIEW

**Comment by mike-wendt** [comment]
@rlratzel updated the status messages so this is the output you get:

### errror
```
(base) mwendt-mlt:tmp mwendt$ ./gpuci_conda_retry conda list
CondaHTTPError:
    [gpuci_conda_retry] Retrying, found 'CondaHTTPError:' in output...
    [gpuci_conda_retry] 1 OF 3 -> sleeping for 5 seconds...
    [gpuci_conda_retry] sleep done...
CondaHTTPError:
    [gpuci_conda_retry] Retrying, found 'CondaHTTPError:' in output...
    [gpuci_conda_retry] 2 OF 3 -> sleeping for 5 seconds...
    [gpuci_conda_retry] sleep done...
CondaHTTPError:
    [gpuci_conda_retry] Retrying, found 'CondaHTTPError:' in output...
    [gpuci_conda_retry] 3 OF 3 -> sleeping for 5 seconds...
    [gpuci_conda_retry] sleep done...
CondaHTTPError:
    [gpuci_conda_retry] Retrying, found 'CondaHTTPError:' in output...
(base) mwendt-mlt:tmp mwendt$ ./gpuci_conda_retry conda list

CommandNotFoundError: No command 'conda conda'.

    [gpuci_conda_retry] Exiting, no retryable conda errors detected: 'ChecksumMismatchError:' or 'CondaHTTPError:'
    [gpuci_conda_retry] conda returned non-zero code: 1
```

### successful
```
(base) mwendt-mlt:tmp mwendt$ ./gpuci_conda_retry list
# packages in environment at /Users/mwendt/miniconda3:
#
# Name                    Version                   Build  Channel
anaconda-client           1.7.2                      py_0    conda-forge
```

LMK what you think. I tried doing a PR into your branch but it didn't work.

**Comment by mike-wendt** [comment]
@rlratzel the only thing I could see that is missing is on the error run above is the lack of a "out of tries" message

something like
```
...
    [gpuci_conda_retry] sleep done...
CondaHTTPError:
    [gpuci_conda_retry] Exiting, reached max retries...
    [gpuci_conda_retry] conda returned non-zero code: 1
```

**Comment by mike-wendt** [comment]
@rlratzel here's the current output with the latest change:
```
(base) mwendt-mlt:tmp mwendt$ ./gpuci_conda_retry conda
CondaHTTPError:
    [gpuci_conda_retry] conda returned exit code: 1
    [gpuci_conda_retry] Retrying, found 'CondaHTTPError:' in output...
    [gpuci_conda_retry] Waiting, retry 1 of 3 -> sleeping for 5 seconds...
    [gpuci_conda_retry] Starting, retry 1 of 3 -> sleep done...
CondaHTTPError:
    [gpuci_conda_retry] conda returned exit code: 1
    [gpuci_conda_retry] Retrying, found 'CondaHTTPError:' in output...
    [gpuci_conda_retry] Waiting, retry 2 of 3 -> sleeping for 5 seconds...
    [gpuci_conda_retry] Starting, retry 2 of 3 -> sleep done...
CondaHTTPError:
    [gpuci_conda_retry] conda returned exit code: 1
    [gpuci_conda_retry] Retrying, found 'CondaHTTPError:' in output...
    [gpuci_conda_retry] Waiting, retry 3 of 3 -> sleeping for 5 seconds...
    [gpuci_conda_retry] Starting, retry 3 of 3 -> sleep done...
CondaHTTPError:
    [gpuci_conda_retry] conda returned exit code: 1
    [gpuci_conda_retry] Exiting, reached max retries...
```

**Comment by rlratzel** [comment]
> CondaHTTPError:
>     [gpuci_conda_retry] conda returned exit code: 1
>     [gpuci_conda_retry] Exiting, reached max retries...
> ```
Looks good to me, thanks.

**Pull request merged**
